import React, { useState, useEffect } from "react";
import {
  FileText,
  Copy,
  Check,
  X,
  RefreshCw,
  FileSpreadsheet,
  Globe,
  ExternalLink,
} from "lucide-react";

interface ReportModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const ReportModal: React.FC<ReportModalProps> = ({ isOpen, onClose }) => {
  const [reportText, setReportText] = useState("");
  const [htmlReport, setHtmlReport] = useState("");
  const [activeView, setActiveView] = useState<"text" | "html">("text");
  const [isLoading, setIsLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);

  useEffect(() => {
    if (isOpen) {
      setIsLoading(true);
      Promise.all([
        fetch("/api/finance/report?format=text").then((r) => r.json()),
        fetch("/api/finance/report?format=html").then((r) => r.text()),
      ])
        .then(([textData, htmlData]) => {
          if (textData && textData.success) {
            setReportText(textData.content);
          }
          if (htmlData) {
            setHtmlReport(htmlData);
          }
        })
        .catch(console.error)
        .finally(() => setIsLoading(false));
    }
  }, [isOpen]);

  const handleCopy = () => {
    navigator.clipboard.writeText(reportText).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const handleDownloadCsv = async () => {
    try {
      setIsDownloading(true);
      const res = await fetch("/api/finance/report?format=csv");
      if (!res.ok) throw new Error("Failed to generate CSV");
      const blob = await res.blob();
      const blobUrl = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = blobUrl;
      a.download = "financial_transactions.csv";
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      setTimeout(() => window.URL.revokeObjectURL(blobUrl), 1000);
    } catch (err: any) {
      console.error("CSV download error:", err);
    } finally {
      setIsDownloading(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl max-w-4xl w-full p-6 shadow-2xl border border-slate-200 flex flex-col h-[85vh]">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-slate-100 pb-4 mb-4">
          <div className="flex items-center space-x-2.5">
            <div className="p-2 rounded-lg bg-emerald-50 border border-emerald-100 text-emerald-700">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-slate-900">
                Executive Financial Reports & Data Export
              </h3>
              <p className="text-xs text-slate-500">
                Official reconciled financial statements generated by the Python reporting engine
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-100 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Action bar and Tab Switcher */}
        <div className="flex flex-wrap items-center justify-between gap-3 p-3 bg-slate-50 border border-slate-200 rounded-xl mb-4">
          <div className="flex items-center space-x-2">
            <button
              onClick={() => setActiveView("text")}
              className={`px-3 py-1.5 text-xs font-semibold rounded-lg transition-colors ${
                activeView === "text"
                  ? "bg-slate-900 text-white shadow-xs"
                  : "bg-white text-slate-700 hover:bg-slate-100 border border-slate-300"
              }`}
            >
              <FileText className="w-3.5 h-3.5 inline mr-1" />
              Audit Text Report
            </button>
            <button
              onClick={() => setActiveView("html")}
              className={`px-3 py-1.5 text-xs font-semibold rounded-lg transition-colors ${
                activeView === "html"
                  ? "bg-slate-900 text-white shadow-xs"
                  : "bg-white text-slate-700 hover:bg-slate-100 border border-slate-300"
              }`}
            >
              <Globe className="w-3.5 h-3.5 inline mr-1 text-blue-500" />
              Styled Statement
            </button>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={handleDownloadCsv}
              disabled={isDownloading}
              className="inline-flex items-center px-3 py-1.5 text-xs font-semibold rounded-lg text-slate-700 bg-white hover:bg-slate-100 border border-slate-300 transition-colors shadow-2xs disabled:opacity-50"
            >
              <FileSpreadsheet className="w-3.5 h-3.5 mr-1.5 text-emerald-600" />
              {isDownloading ? "Exporting..." : "Download CSV Ledger"}
            </button>

            <a
              href="/api/finance/report.html"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center px-3 py-1.5 text-xs font-semibold rounded-lg text-slate-700 bg-white hover:bg-slate-100 border border-slate-300 transition-colors shadow-2xs"
            >
              <ExternalLink className="w-3.5 h-3.5 mr-1.5 text-blue-600" />
              Open in Tab
            </a>

            {activeView === "text" && (
              <button
                onClick={handleCopy}
                className="inline-flex items-center px-3 py-1.5 text-xs font-semibold rounded-lg text-white bg-slate-900 hover:bg-slate-800 transition-colors shadow-2xs"
              >
                {copied ? (
                  <>
                    <Check className="w-3.5 h-3.5 mr-1 text-emerald-400" /> Copied
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5 mr-1" /> Copy Text
                  </>
                )}
              </button>
            )}
          </div>
        </div>

        {/* Report Content View */}
        <div className="flex-1 rounded-xl overflow-hidden border border-slate-200">
          {isLoading ? (
            <div className="h-full flex items-center justify-center text-slate-400 text-xs bg-slate-900">
              <RefreshCw className="w-4 h-4 animate-spin mr-2" /> Generating executive report...
            </div>
          ) : activeView === "text" ? (
            <div className="h-full bg-slate-900 p-4 overflow-auto">
              <pre className="font-mono text-emerald-400 text-xs whitespace-pre leading-relaxed select-text">
                {reportText}
              </pre>
            </div>
          ) : (
            <iframe
              srcDoc={htmlReport}
              title="Financial Statement"
              className="w-full h-full border-0 bg-white"
              sandbox="allow-same-origin allow-scripts"
            />
          )}
        </div>

        {/* Footer */}
        <div className="pt-4 flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-2 text-xs font-medium text-slate-700 bg-slate-100 hover:bg-slate-200 rounded-lg transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
