import React, { useState, useEffect } from "react";
import {
  FileText,
  Download,
  Copy,
  Check,
  X,
  RefreshCw,
  FileSpreadsheet,
  Globe,
} from "lucide-react";

interface ReportModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const ReportModal: React.FC<ReportModalProps> = ({ isOpen, onClose }) => {
  const [reportText, setReportText] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (isOpen) {
      setIsLoading(true);
      fetch("/api/finance/report?format=text")
        .then((res) => res.json())
        .then((data) => {
          if (data.success) {
            setReportText(data.content);
          }
        })
        .catch(console.error)
        .finally(() => setIsLoading(false));
    }
  }, [isOpen]);

  const handleCopy = () => {
    navigator.clipboard.writeText(reportText).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const handleDownloadCsv = () => {
    window.location.href = "/api/finance/report?format=csv";
  };

  const handleOpenHtmlReport = () => {
    window.open("/api/finance/report?format=html", "_blank");
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl max-w-3xl w-full p-6 shadow-2xl border border-slate-200 flex flex-col h-[80vh]">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-slate-100 pb-4 mb-4">
          <div className="flex items-center space-x-2.5">
            <div className="p-2 rounded-lg bg-emerald-50 border border-emerald-100 text-emerald-700">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-slate-900">
                Executive Financial Reports & Data Export
              </h3>
              <p className="text-xs text-slate-500">
                Official reconciled financial statements generated by the Python reporting engine
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-100 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Action bar for downloads */}
        <div className="flex flex-wrap items-center justify-between gap-3 p-3 bg-slate-50 border border-slate-200 rounded-xl mb-4">
          <span className="text-xs font-semibold text-slate-700">
            Export Formats:
          </span>
          <div className="flex items-center space-x-2">
            <button
              onClick={handleOpenHtmlReport}
              className="inline-flex items-center px-3 py-1.5 text-xs font-semibold rounded-lg text-slate-700 bg-white hover:bg-slate-100 border border-slate-300 transition-colors shadow-2xs"
            >
              <Globe className="w-3.5 h-3.5 mr-1.5 text-blue-600" />
              View Styled HTML Statement
            </button>
            <button
              onClick={handleDownloadCsv}
              className="inline-flex items-center px-3 py-1.5 text-xs font-semibold rounded-lg text-slate-700 bg-white hover:bg-slate-100 border border-slate-300 transition-colors shadow-2xs"
            >
              <FileSpreadsheet className="w-3.5 h-3.5 mr-1.5 text-emerald-600" />
              Download CSV Ledger
            </button>
            <button
              onClick={handleCopy}
              className="inline-flex items-center px-3 py-1.5 text-xs font-semibold rounded-lg text-white bg-slate-900 hover:bg-slate-800 transition-colors shadow-2xs"
            >
              {copied ? (
                <>
                  <Check className="w-3.5 h-3.5 mr-1 text-emerald-400" /> Copied Text
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5 mr-1" /> Copy Text
                </>
              )}
            </button>
          </div>
        </div>

        {/* Report Preview */}
        <div className="flex-1 bg-slate-900 rounded-xl p-4 overflow-auto border border-slate-800">
          {isLoading ? (
            <div className="h-full flex items-center justify-center text-slate-400 text-xs">
              <RefreshCw className="w-4 h-4 animate-spin mr-2" /> Generating executive report...
            </div>
          ) : (
            <pre className="font-mono text-emerald-400 text-xs whitespace-pre leading-relaxed select-text">
              {reportText}
            </pre>
          )}
        </div>

        {/* Footer */}
        <div className="pt-4 flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-2 text-xs font-medium text-slate-700 bg-slate-100 hover:bg-slate-200 rounded-lg transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
